### ISSUE TITLE
Enable CORS for all origins

### ISSUE THREAD

**Issue by willrogers** [dls-controls/coniql#20]
I am running a demo Coniql server and it is being used by two separate web apps: cs-web-proto and @AlexanderWells-diamond 's pts_webserver.

For this to work it needs CORS enabled for both those servers, or more flexibly all origins (which I have in practice patched into the build).

Do you still think we should restrict CORS or can we change it to `*`?

@thomascobb

**Comment by AlexanderWells-diamond** [comment]
For a bit more into, my pts_webserver is running in Kubernetes and so while it currently has a static IP address, I don't know if that guaranteed to stay the same after restarts (or complete delete + recreate scenarios). Hence it'd be difficult to allow CORS, unless we can just allow everything from the Kubernetes cluster (I believe that's 172.23.*). 

I'm also not convinced we need to protect the data coming from Coniql, at least not for the Queries and Subscriptions. From my understanding, if you can access Coniql you can at the very least access `caget` from the command line and so have roughly the same data available. The important one to protect would be the Mutation, but that won't even work at the moment because it's in Kubernetes and not in the primary network?

**Comment by thomascobb** [comment]
I'd be happy to allow `*` if we make it a commandline option to enable, like https://github.com/dls-controls/scanspec/blob/master/scanspec/cli.py#L45

**Comment by thomascobb** [comment]
I'd remove it, so then we are consistent with scanspec has.
